### ISSUE TITLE
Edit/Update the About section in all Tchap repos

### ISSUE THREAD

**Issue by giomfo** [dinsic-pim/tchap-welcome#2]
We should update the "About" section in all Tchap repo

For example Tchap-Android-v2 mentions element.io as web site:
![image](https://user-images.githubusercontent.com/8969772/148532999-45612b05-0851-4857-b7c9-228bbd72142f.png)

assigned to @jdauphant for triage

**Comment by giomfo** [comment]
@jdauphant I failed to edit "Projects" option for this issue. I would like to add to the project Tchap...
is it a permission limitation?

**Comment by jdauphant** [comment]
@giomfo Should be good now ? I have increased the level of rights

**Comment by jdauphant** [comment]
I have updated all the projet description
